# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_Search_Substitute.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 250)
        Dialog.setMinimumSize(QtCore.QSize(450, 250))
        Dialog.setMaximumSize(QtCore.QSize(450, 250))
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 431, 231))
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.Tab_Search = QtWidgets.QWidget()
        self.Tab_Search.setObjectName("Tab_Search")
        self.label_searchContent = QtWidgets.QLabel(self.Tab_Search)
        self.label_searchContent.setGeometry(QtCore.QRect(30, 30, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        self.label_searchContent.setFont(font)
        self.label_searchContent.setObjectName("label_searchContent")
        self.label_option = QtWidgets.QLabel(self.Tab_Search)
        self.label_option.setGeometry(QtCore.QRect(30, 70, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        self.label_option.setFont(font)
        self.label_option.setObjectName("label_option")
        self.lineEdit_searchContent = QtWidgets.QLineEdit(self.Tab_Search)
        self.lineEdit_searchContent.setGeometry(QtCore.QRect(110, 20, 231, 41))
        self.lineEdit_searchContent.setObjectName("lineEdit_searchContent")
        self.pushButton_highLight = QtWidgets.QPushButton(self.Tab_Search)
        self.pushButton_highLight.setGeometry(QtCore.QRect(90, 160, 151, 31))
        self.pushButton_highLight.setObjectName("pushButton_highLight")
        self.pushButton_cancel = QtWidgets.QPushButton(self.Tab_Search)
        self.pushButton_cancel.setGeometry(QtCore.QRect(340, 160, 71, 31))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.pushButton_searchNext = QtWidgets.QPushButton(self.Tab_Search)
        self.pushButton_searchNext.setGeometry(QtCore.QRect(250, 160, 81, 31))
        self.pushButton_searchNext.setObjectName("pushButton_searchNext")
        self.PushButton_more = QtWidgets.QPushButton(self.Tab_Search)
        self.PushButton_more.setGeometry(QtCore.QRect(10, 160, 51, 31))
        self.PushButton_more.setObjectName("PushButton_more")
        self.tabWidget.addTab(self.Tab_Search, "")
        self.Tab_Substitute = QtWidgets.QWidget()
        self.Tab_Substitute.setObjectName("Tab_Substitute")
        self.lineEdit_searchContent_2 = QtWidgets.QLineEdit(self.Tab_Substitute)
        self.lineEdit_searchContent_2.setGeometry(QtCore.QRect(110, 20, 301, 41))
        self.lineEdit_searchContent_2.setObjectName("lineEdit_searchContent_2")
        self.label_searchContent_2 = QtWidgets.QLabel(self.Tab_Substitute)
        self.label_searchContent_2.setGeometry(QtCore.QRect(30, 30, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        self.label_searchContent_2.setFont(font)
        self.label_searchContent_2.setObjectName("label_searchContent_2")
        self.PushButton_more_2 = QtWidgets.QPushButton(self.Tab_Substitute)
        self.PushButton_more_2.setGeometry(QtCore.QRect(10, 160, 51, 31))
        self.PushButton_more_2.setObjectName("PushButton_more_2")
        self.pushButton_cancel_2 = QtWidgets.QPushButton(self.Tab_Substitute)
        self.pushButton_cancel_2.setGeometry(QtCore.QRect(340, 160, 71, 31))
        self.pushButton_cancel_2.setObjectName("pushButton_cancel_2")
        self.pushButton_searchNext_2 = QtWidgets.QPushButton(self.Tab_Substitute)
        self.pushButton_searchNext_2.setGeometry(QtCore.QRect(250, 160, 81, 31))
        self.pushButton_searchNext_2.setObjectName("pushButton_searchNext_2")
        self.pushButton_singleSubstitute_2 = QtWidgets.QPushButton(self.Tab_Substitute)
        self.pushButton_singleSubstitute_2.setGeometry(QtCore.QRect(70, 160, 61, 31))
        self.pushButton_singleSubstitute_2.setObjectName("pushButton_singleSubstitute_2")
        self.label_option_2 = QtWidgets.QLabel(self.Tab_Substitute)
        self.label_option_2.setGeometry(QtCore.QRect(30, 70, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        self.label_option_2.setFont(font)
        self.label_option_2.setObjectName("label_option_2")
        self.pushButton_allSubstitute_2 = QtWidgets.QPushButton(self.Tab_Substitute)
        self.pushButton_allSubstitute_2.setGeometry(QtCore.QRect(140, 160, 101, 31))
        self.pushButton_allSubstitute_2.setObjectName("pushButton_allSubstitute_2")
        self.label_substitute_2 = QtWidgets.QLabel(self.Tab_Substitute)
        self.label_substitute_2.setGeometry(QtCore.QRect(30, 112, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        self.label_substitute_2.setFont(font)
        self.label_substitute_2.setObjectName("label_substitute_2")
        self.lineEdit_substituteContent_2 = QtWidgets.QLineEdit(self.Tab_Substitute)
        self.lineEdit_substituteContent_2.setGeometry(QtCore.QRect(110, 100, 301, 41))
        self.lineEdit_substituteContent_2.setObjectName("lineEdit_substituteContent_2")
        self.tabWidget.addTab(self.Tab_Substitute, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_searchContent.setText(_translate("Dialog", "查找内容:"))
        self.label_option.setText(_translate("Dialog", "选项:               区分全/半角"))
        self.pushButton_highLight.setText(_translate("Dialog", "阅读突出显示(开/关)"))
        self.pushButton_cancel.setText(_translate("Dialog", "取消"))
        self.pushButton_searchNext.setText(_translate("Dialog", "查找下一个"))
        self.PushButton_more.setText(_translate("Dialog", "更多 >>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Search), _translate("Dialog", "查找"))
        self.label_searchContent_2.setText(_translate("Dialog", "查找内容:"))
        self.PushButton_more_2.setText(_translate("Dialog", "更多 >>"))
        self.pushButton_cancel_2.setText(_translate("Dialog", "取消"))
        self.pushButton_searchNext_2.setText(_translate("Dialog", "查找下一个"))
        self.pushButton_singleSubstitute_2.setText(_translate("Dialog", "替换"))
        self.label_option_2.setText(_translate("Dialog", "选项:               区分全/半角"))
        self.pushButton_allSubstitute_2.setText(_translate("Dialog", "全部替换"))
        self.label_substitute_2.setText(_translate("Dialog", "替换为:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_Substitute), _translate("Dialog", "替换"))

