# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_Top20.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(528, 603)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(310, 550, 171, 31))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(290, 20, 211, 501))
        self.textBrowser.setObjectName("textBrowser")
        self.tableWidget_Freq = QtWidgets.QTableWidget(Dialog)
        self.tableWidget_Freq.setGeometry(QtCore.QRect(20, 20, 241, 571))
        self.tableWidget_Freq.setObjectName("tableWidget_Freq")
        self.tableWidget_Freq.setColumnCount(2)
        self.tableWidget_Freq.setRowCount(19)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        item.setFont(font)
        self.tableWidget_Freq.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        item.setFont(font)
        self.tableWidget_Freq.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(14, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(15, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(16, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(17, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(17, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(18, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Freq.setItem(18, 1, item)
        self.tableWidget_Freq.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget_Freq.horizontalHeader().setMinimumSectionSize(25)
        self.tableWidget_Freq.verticalHeader().setDefaultSectionSize(28)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableWidget_Freq.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "2"))
        item = self.tableWidget_Freq.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "3"))
        item = self.tableWidget_Freq.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "4"))
        item = self.tableWidget_Freq.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "5"))
        item = self.tableWidget_Freq.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "6"))
        item = self.tableWidget_Freq.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "7"))
        item = self.tableWidget_Freq.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "8"))
        item = self.tableWidget_Freq.verticalHeaderItem(8)
        item.setText(_translate("Dialog", "9"))
        item = self.tableWidget_Freq.verticalHeaderItem(9)
        item.setText(_translate("Dialog", "10"))
        item = self.tableWidget_Freq.verticalHeaderItem(10)
        item.setText(_translate("Dialog", "11"))
        item = self.tableWidget_Freq.verticalHeaderItem(11)
        item.setText(_translate("Dialog", "12"))
        item = self.tableWidget_Freq.verticalHeaderItem(12)
        item.setText(_translate("Dialog", "13"))
        item = self.tableWidget_Freq.verticalHeaderItem(13)
        item.setText(_translate("Dialog", "14"))
        item = self.tableWidget_Freq.verticalHeaderItem(14)
        item.setText(_translate("Dialog", "15"))
        item = self.tableWidget_Freq.verticalHeaderItem(15)
        item.setText(_translate("Dialog", "16"))
        item = self.tableWidget_Freq.verticalHeaderItem(16)
        item.setText(_translate("Dialog", "17"))
        item = self.tableWidget_Freq.verticalHeaderItem(17)
        item.setText(_translate("Dialog", "18"))
        item = self.tableWidget_Freq.verticalHeaderItem(18)
        item.setText(_translate("Dialog", "20"))
        item = self.tableWidget_Freq.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "单词"))
        item = self.tableWidget_Freq.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "出现次数"))
        __sortingEnabled = self.tableWidget_Freq.isSortingEnabled()
        self.tableWidget_Freq.setSortingEnabled(False)
        item = self.tableWidget_Freq.item(0, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(0, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(1, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(1, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(2, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(2, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(3, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(3, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(4, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(4, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(5, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(5, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(6, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(6, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(7, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(7, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(8, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(8, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(9, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(9, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(10, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(10, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(11, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(11, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(12, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(12, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(13, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(13, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(14, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(14, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(15, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(15, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(16, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(16, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(17, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(17, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(18, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_Freq.item(18, 1)
        item.setText(_translate("Dialog", "1"))
        self.tableWidget_Freq.setSortingEnabled(__sortingEnabled)

